language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: deploy-test
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully deployed to AWS'
env:
  global:
    secure: TtkoUeHfD+tFUV+NX4ekTUvUuY6BjWk7crnsrXwAXR6pjCly2NabSDuejXW84o+29+XxD2lu94sfu3+lfY5zBUuJDdUeu+ZWF9c30q0iklyH3hpe72Esn8PPcvNl/CCM0VZZhHX55gyNeguUVRDA5RHTgw8+13avwFM7icGea9n1qaeCJdkD+yp2D8Sja6cB9H2Q+tPjZ5dr02i7DKxFVUIfbFaY9h9ZvEHPawWxp2LLbZif7y3xRcUJtiLXZ0C4b4p1IcnDLNBFWl2AwXnajPplLB3TYHb4A1Y4oyaO93KU48omuqAcpmtl1N1IaxBplGgQRzeqK7BJt7GKX+VK5KXAmruhYoo/zFmLInYX2BM2iBkxXmgFtWUgKETApRb/8HZHLKVnhzbQW2FZ0uQh9BVAooBnd4beuF15zsra5sd4sN0UQExtQhyicDJBNIypvl2ehRXle6AMfHga9S4CIrYsx2jFSNpv1xX1fkFC1C0FXaMYk6JoIuXWziAtCSTAkUXeRxvm/KV4eayePIebCqZ+MyQguU9N/izxO3fvzGdChDc1rzx1lf80kB3TCX+f6KM3RqFeNF0D3Sr9GgIZUVsSpji3NCHmnKbRGMbzWw3cYrxh8AWy3uO8V0eFEuddOt5vQv3y4K3yEMngirGh9A700NspAUAQtN+977TNniM=
