language: node_js
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully deployed to AWS'
env:
  global:
    secure: y/xKqubhNmeUDWDwfDrHS+i3CLIdDcgDGcS4hzfYE4hvGEy+VaNMiawdSe5+EvIg3PGQ+6a3sbEY0DlyOffrpDp5+3eEVT/rvXNAMJWsfb/Y5iafhkMoWGK1zwIRfHaHcIXeWZPvZthIdM0WaCi1SOIlMKqL55J5XjM8mHtHBq0iSltYmL2zu4ab03U7d8NHl1OszYdv9qZBiNUz/q8VEbPy9ty3X/siCRBRJeNKUdPoteWCVPzR+0Pl5F4RLGj+gxbB7dbkVMYfPKKJFndKd2q2G8N18RZXun326tZxvNQW3EVtkq6SsVOYqi9tyr2J6iX7nwekdriFG+9MLlrtLV5MPJzS9bu5VJwGiJyJudDAD2iSUk4hQJV8VvFsuUseelQa4ue+pUugADv93nGMAVQMJ/aPXtgpPWJr/MLqTV+vmAKK3SpMx3k1+oyoVPsW0cQWWby8foQ84kZM+GLdUTEJ6++OSoaehlsbZQHQubEhrSnWsMrvgvEfcA+lAfFEui9H7BCpgKs8C1ImdlYnyo+XXJRBY8wZWrtk9ZksLjuUrDh8KkVZJNBZfHo56OSCpgAdrnYIKwkQ/u8bYs2s5ZkpxnlH/Iv5EL8qM4p0Et26kj3Ye4maGmS5rVKEQsF7WSwM6GRru9yu0AXvsn/wjKGO2Vhoht0SDo6Tl07GNGc=
